baseURL = "https://dk3156.github.io/dongje.kim/"
languageCode = 'en-us'
title = 'DONGJE KIM'
theme = "anatole"
enableEmoji = true

[params]
title = "Dongje Kim"
author = "dongje kim"
email = "djkim0424@gmail.com"
description = "Portfolio"
mainSections = ["experience", "projects", "skills", "blog"]
profilePicture = "images/tiger.png"
BookSection = '/'

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "experience"
  weight = 2
  identifier = "experience"
  url = "/experience/work/"

  [[menu.main]]
  name = "project"
  weight = 3
  identifier = "project"
  url = "/projects/"

  [[menu.main]]
  name = "blog"
  weight = 4
  identifier = "blog"
  url = "/blog/"